# Generated by Django 6.1.1 on 2026-10-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projects_client_projectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
