# Generated by Django 6.1.1 on 2026-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projects_client_alter_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
