# Generated by Django 6.1.1 on 2026-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projectimages_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
